version: '3.8'
services:
  db:
    image: postgres
    networks:
      - backend
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/pgsql/data

  backend:
    build: ./backend
    # image: devcontainerdemonstration_backend:latest
    restart: unless-stopped
    networks:
      - frontend
      - backend
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    networks:
      - frontend
    depends_on:
      - backend
    ports:
      - 3000:3000

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  db-data:
