version: '3.8' # Updated to a more recent version

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    command: python main.py
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      # Use depends_on instead of links
      - db
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    command: nginx -g "daemon off;" -c /app/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend

volumes:
  postgres-data:


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
