version: '3.8'
services:
  db:
    image: postgres
    networks:
      - backend
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/pgsql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    # image: devcontainerdemonstration_backend:latest
    restart: unless-stopped
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    networks:
      - frontend
    depends_on:
      - backend
    ports:
      - 3000:3000

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  db-data:
